root_artifact: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  source_url: "https://github.com/HimmatMagar/datae/raw/refs/heads/main/general_knowledge_qa.zip"
  zip_file: artifact/data_ingestion/data.zip
  unzip_file: artifact/data_ingestion


model_training:
  root_dir: artifact/model
  data_path: artifact/data_ingestion/general_knowledge_qa.csv